CREATE TABLE CONTRACT.HOUSE_SOURCE
(
  ID varchar(32) NOT NULL,
  POWER_CARD_NUMBER varchar(50) NOT NULL,
  CREDENTIALS_TYPE varchar(32) NOT NULL,
  CREDENTIALS_NUMBER varchar(100) NOT NULL,
  OWNER_NAME varchar(50) NOT NULL,
  TEL varchar(16) NOT NULL,
  MASTER_GROUP_ID varchar(32) NOT NULL,
  VERSION bigint NOT NULL,
  SHOW_TYPE varchar(20) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.HOUSE_SELL_INFO
(
  ID varchar(32) NOT NULL,
  TITLE varchar(64) NOT NULL,
  TAGS varchar(512),
  DESCRIPTION varchar(512),
  ENVIRONMENT varchar(512),
  LAT decimal(18,14),
  LNG decimal(18,14),
  ZOOM int,
  ROOM_COUNT int NOT NULL,
  LIVING_ROOM int NOT NULL,
  LOCAL_AREA varchar(32),
  SCHOOL_AREA varchar(32),
  METRO_AREA varchar(32),
  DECORATE varchar(512),
  ELEVATOR boolean,
  COVER varchar(32),
  IN_FLOOR int NOT NULL,
  STATUS varchar(20) NOT NULL,
  TYPE varchar(20) NOT NULL,
  APPLY_TIME datetime NOT NULL,
  CHECK_TIME datetime NOT NULL,
  CREATE_YEAR int NOT NULL,
  SOURCE_ID varchar(32) NOT NULL,
  DIRECTION varchar(32),
  HOUSE_CODE varchar(32) NOT NULL,
  USE_TYPE varchar(32) NOT NULL,
  IN_FLOOR_NAME varchar(50) NOT NULL,
  HOUSE_AREA decimal(18,3) NOT NULL,
  USE_AREA decimal(18,3),
  STRUCTURE varchar(32) NOT NULL,
  ADDRESS varchar(200) NOT NULL,
  SALE_TITLE varchar(200) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


ALTER TABLE CONTRACT.HOUSE_SELL_INFO
  ADD FOREIGN KEY (ID)
REFERENCES CONTRACT.HOUSE_SOURCE (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

