SET SESSION FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS CONTRACT.SELL_SHOW_IMG;
DROP TABLE IF EXISTS CONTRACT.HOUSE_SELL_INFO;
DROP TABLE IF EXISTS CONTRACT.SELL_PROXY_PERSON;
DROP TABLE IF EXISTS CONTRACT.HOUSE_SOURCE;
DROP TABLE IF EXISTS CONTRACT.COMPANY_SELL_INFO;
DROP TABLE IF EXISTS CONTRACT.SELL_AREA;

CREATE TABLE CONTRACT.MONEY_MANAGER
(
  ID varchar(32) NOT NULL,
  BANK varchar(32) NOT NULL,
  BANK_NAME varchar(128) NOT NULL,
  ACCOUNT varchar(32) NOT NULL,
  MONEY decimal(19,4) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE CONTRACT.MONEY_MANAGER
  ADD FOREIGN KEY (ID)
REFERENCES CONTRACT.HOUSE_CONTRACT (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

CREATE TABLE CONTRACT.OLD_HOUSE_MONEY
(
  ID varchar(32) NOT NULL,
  BANK_NAME varchar(512) NOT NULL,
  CARD_NAME varchar(50) NOT NULL,
  CARD_NUMBER varchar(128) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE CONTRACT.OLD_HOUSE_MONEY
  ADD FOREIGN KEY (ID)
REFERENCES CONTRACT.MONEY_MANAGER (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

CREATE TABLE CONTRACT.SELL_SHOW_IMG
(
  ID varchar(32) NOT NULL,
  TITLE varchar(64) NOT NULL,
  DESCRIPTION varchar(512),
  HOUSE_SELL_INFO varchar(32) NOT NULL,
  PRI int NOT NULL ,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

CREATE TABLE CONTRACT.HOUSE_SELL_INFO
(
  ID varchar(32) NOT NULL,
  TITLE varchar(64) NOT NULL,
  TAGS varchar(512),
  DESCRIPTION varchar(512),
  ENVIRONMENT varchar(512),
  LAT decimal(18,14),
  LNG decimal(18,14),
  ZOOM int,
  ROOM_COUNT int NOT NULL,
  LIVING_ROOM int NOT NULL,
  METRO_AREA varchar(32),
  DECORATE varchar(512),
  ELEVATOR boolean,
  COVER varchar(32),
  IN_FLOOR int NOT NULL,
  CREATE_YEAR int NOT NULL,
  DIRECTION varchar(32),
  ADDRESS varchar(200) NOT NULL,
  LOCAL_AREA varchar(32),
  SCHOOL_AREA varchar(32),
  FLOOR_COUNT int NOT NULL,
  KITCHEN_COUNT int NOT NULL,
  TOILET_COUNT int NOT NULL,
  PRICE decimal(19,4) NOT NULL,
  SUM_PRICE decimal(19,4) NOT NULL,
  END_TIME datetime,
  TIME_AREA_TYPE varchar(16) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.HOUSE_SOURCE
(
  ID varchar(32) NOT NULL,
  POWER_CARD_NUMBER varchar(50) NOT NULL,
  CREDENTIALS_TYPE varchar(32) NOT NULL,
  CREDENTIALS_NUMBER varchar(100) NOT NULL,
  OWNER_NAME varchar(50) NOT NULL,
  TEL varchar(16) NOT NULL,
  MASTER_GROUP_ID varchar(32) NOT NULL,
  VERSION bigint NOT NULL,
  CHECK_VIEW varchar(200),
  HOUSE_CODE varchar(32) NOT NULL,
  SOURCE_ID varchar(32) NOT NULL,
  TYPE varchar(20) NOT NULL,
  APPLY_TIME datetime NOT NULL,
  STATUS varchar(20) NOT NULL,
  SEARCH_KEY varchar(1024),
  CHECK_TIME datetime NOT NULL,
  BUSINESS_ID varchar(32),
  MESSAGES longtext,
  UPDATE_TIME timestamp NOT NULL,
  POWER_CARD_TYPE varchar(16) NOT NULL,
  ALLOW_JOIN boolean NOT NULL,
  ADDRESS varchar(200),
  MSG_TYPE varchar(20),
  USE_TYPE varchar(32) NOT NULL,
  MAP_NUMBER varchar(4),
  BLOCK_NUMBER varchar(10) NOT NULL,
  BUILD_NUMBER varchar(24) NOT NULL,
  HOUSE_ORDER varchar(20) NOT NULL,
  STRUCTURE varchar(32),
  IN_FLOOR_NAME varchar(50),
  FLOOR_COUNT int,
  DISTRICT varchar(32) NOT NULL,
  HOUSE_AREA decimal(18,3) NOT NULL,
  USE_AREA decimal(18,3),
  DESIGN_USE_TYPE varchar(512) NOT NULL,
  PRICE decimal(19,4) NOT NULL,
  SUM_PRICE decimal(19,4) NOT NULL,
  TIME_AREA_TYPE varchar(16) NOT NULL,
  END_TIME datetime,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;




CREATE TABLE CONTRACT.SELL_PROXY_PERSON
(
  ID varchar(32) NOT NULL,
  TYPE varchar(16) NOT NULL,
  PERSON_NAME varchar(50) NOT NULL,
  CREDENTIALS_TYPE varchar(32) NOT NULL,
  CREDENTIALS_NUMBER varchar(100) NOT NULL,
  ADDRESS varchar(200),
  TEL varchar(15) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.COMPANY_SELL_INFO
(
  GROUP_ID varchar(32) NOT NULL,
  ID varchar(32) NOT NULL,
  HOUSE_SOURCE varchar(32) NOT NULL,
  CONTRACT longtext,
  TITLE varchar(100) NOT NULL,
  MEMO longtext,
  SALE_CONTRACT varchar(32),
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

CREATE TABLE CONTRACT.NUMBER_SEQUENCE
(
  ID varchar(32) NOT NULL,
  TYPE varchar(16) NOT NULL,
  NUMBER bigint NOT NULL,
  VERSION bigint NOT NULL,
  UPDATE_TIME datetime NOT NULL,
  MIN_LEN int NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE CONTRACT.SELL_SHOW_IMG
  ADD FOREIGN KEY (HOUSE_SELL_INFO)
REFERENCES CONTRACT.HOUSE_SELL_INFO (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE CONTRACT.HOUSE_SELL_INFO
  ADD FOREIGN KEY (ID)
REFERENCES CONTRACT.HOUSE_SOURCE (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE CONTRACT.SELL_PROXY_PERSON
  ADD FOREIGN KEY (ID)
REFERENCES CONTRACT.HOUSE_SOURCE (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE CONTRACT.COMPANY_SELL_INFO
  ADD FOREIGN KEY (HOUSE_SOURCE)
REFERENCES CONTRACT.HOUSE_SOURCE (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE CONTRACT.COMPANY_SELL_INFO
  ADD FOREIGN KEY (SALE_CONTRACT)
REFERENCES CONTRACT.HOUSE_CONTRACT (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE HOUSE_CONTRACT ADD FILE_ID varchar(32) NULL;
ALTER TABLE HOUSE_CONTRACT ADD COMMIT_TIME datetime NULL;
ALTER TABLE OLD_HOUSE_CONTRACT ADD SELLER_POOL_TYPE VARCHAR(32) NULL;

INSERT INTO CONTRACT.SYSTEM_PARAM(ID,VALUE,TYPE) VALUES('contract_address','http://192.168.248.246/','STRING');

INSERT INTO CONTRACT.SYSTEM_PARAM(ID,VALUE,TYPE) VALUES('map.lat','40.12902283','STRING');
INSERT INTO CONTRACT.SYSTEM_PARAM(ID,VALUE,TYPE) VALUES('map.lng','124.33854311','STRING');
INSERT INTO CONTRACT.SYSTEM_PARAM(ID,VALUE,TYPE) VALUES('map.zoom','14','STRING');

INSERT INTO CONTRACT.SYSTEM_PARAM(ID,VALUE,TYPE) VALUES('ZONE_CODE','DG','STRING');

INSERT INTO HOUSE_INFO.MONEY_BANK(ID,NAME,KEYT,SECRET_TYPE,PRI,ACCOUNT_NUMBER)
    VALUES ('DDBK','丹东银行','a1234567a1234567','NONE',1,'12345678');

-- http://192.168.248.248:8090/api/money/old/contract?bank=DDBK&account=12345678&contract=CDG201803203

-- http://192.168.248.248:8090/bank/money/old/contract/DDBK/12345678/CDG201803203
INSERT INTO MONEY_BUSINESS(ID,BUSINESS,STATUS,BANK,BANK_NAME,ACCOUNT_NUMBER,VER,VERSION,MONEY,CONTRACT)
  VALUES ('test1','WP56-20180320013','CREATED','DDBK','丹东银行','12345678',1,1,2,'ff8080816243019001624329991c000f');
INSERT INTO MONEY_PAY_INFO(ID,BANK_NAME,CARD_NUMBER,CARD_NAME) VALUES ('test1','付款开户行','付款卡号','持卡人姓名');


-- http://192.168.248.248:8090/api/money/old/pay?bank=DDBK&account=12345678
-- http://192.168.248.248:8090/bank/money/old/pay/DDBK/12345678

INSERT INTO MONEY_BUSINESS(ID,BUSINESS,STATUS,BANK,BANK_NAME,ACCOUNT_NUMBER,VER,VERSION,MONEY,CONTRACT)
VALUES ('test2','WP56-20180320012','CREATED','DDBK','丹东银行','12345678',1,1,2,'ff80808162430190016243268e140008');
INSERT INTO MONEY_PAY_INFO(ID,BANK_NAME,CARD_NUMBER,CARD_NAME) VALUES ('test2','付款开户行','付款卡号','持卡人姓名');


INSERT INTO MONEY_BUSINESS(ID,BUSINESS,STATUS,BANK,BANK_NAME,ACCOUNT_NUMBER,VER,VERSION,MONEY,CONTRACT)
VALUES ('test3','WP56-20180320011','CREATED','DDBK','丹东银行','12345678',1,1,2,'ff80808162430190016243234c700001');

INSERT INTO MONEY_PAY_INFO(ID,BANK_NAME,CARD_NUMBER,CARD_NAME) VALUES ('test3','付款开户行','付款卡号','持卡人姓名');


-- curl -X POST --data 'data={"dir":"IN","money":800,"contract":"f5f5f5","seq":"999","time":"2018-3-31 13:08:01","timestamp": "2018-3-31 13:08:01"}' http://192.168.248.248:8090/bank/money/old/report/DDBK/12345678