SET SESSION FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS CONTRACT.SELL_SHOW_IMG;
DROP TABLE IF EXISTS CONTRACT.HOUSE_SELL_INFO;
DROP TABLE IF EXISTS CONTRACT.SELL_PROXY_PERSON;
DROP TABLE IF EXISTS CONTRACT.HOUSE_SOURCE;
DROP TABLE IF EXISTS CONTRACT.COMPANY_SELL_INFO;
DROP TABLE IF EXISTS CONTRACT.SELL_AREA;

CREATE TABLE CONTRACT.SELL_SHOW_IMG
(
  ID varchar(32) NOT NULL,
  TITLE varchar(64) NOT NULL,
  DESCRIPTION varchar(512),
  HOUSE_SELL_INFO varchar(32) NOT NULL,
  PRI int NOT NULL ,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

CREATE TABLE CONTRACT.HOUSE_SELL_INFO
(
  ID varchar(32) NOT NULL,
  TITLE varchar(64) NOT NULL,
  TAGS varchar(512),
  DESCRIPTION varchar(512),
  ENVIRONMENT varchar(512),
  LAT decimal(18,14),
  LNG decimal(18,14),
  ZOOM int,
  ROOM_COUNT int NOT NULL,
  LIVING_ROOM int NOT NULL,
  METRO_AREA varchar(32),
  DECORATE varchar(512),
  ELEVATOR boolean,
  COVER varchar(32),
  IN_FLOOR int NOT NULL,
  CREATE_YEAR int NOT NULL,
  DIRECTION varchar(32),
  USE_TYPE varchar(32) NOT NULL,
  IN_FLOOR_NAME varchar(50) NOT NULL,
  HOUSE_AREA decimal(18,3) NOT NULL,
  USE_AREA decimal(18,3),
  STRUCTURE varchar(32) NOT NULL,
  ADDRESS varchar(200) NOT NULL,
  DISTRICT varchar(32) NOT NULL,
  LOCAL_AREA varchar(32),
  SCHOOL_AREA varchar(32),
  PRICE decimal(19,4) NOT NULL,
  SUM_PRICE decimal(19,4) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

CREATE TABLE CONTRACT.HOUSE_SOURCE
(
  ID varchar(32) NOT NULL,
  POWER_CARD_NUMBER varchar(50) NOT NULL,
  CREDENTIALS_TYPE varchar(32) NOT NULL,
  CREDENTIALS_NUMBER varchar(100) NOT NULL,
  OWNER_NAME varchar(50) NOT NULL,
  TEL varchar(16) NOT NULL,
  MASTER_GROUP_ID varchar(32) NOT NULL,
  VERSION bigint NOT NULL,
  CHECK_VIEW varchar(200),
  HOUSE_CODE varchar(32) NOT NULL,
  SOURCE_ID varchar(32) NOT NULL,
  TYPE varchar(20) NOT NULL,
  APPLY_TIME datetime NOT NULL,
  STATUS varchar(20) NOT NULL,
  SEARCH_KEY varchar(1024),
  SALE_TITLE varchar(200) NOT NULL,
  CHECK_TIME datetime NOT NULL,
  CONTRACT varchar(32),
  BUSINESS_ID varchar(32),
  MESSAGES longtext,
  UPDATE_TIME timestamp NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.HOUSE_SOURCE
(
  ID varchar(32) NOT NULL,
  POWER_CARD_NUMBER varchar(50) NOT NULL,
  CREDENTIALS_TYPE varchar(32) NOT NULL,
  CREDENTIALS_NUMBER varchar(100) NOT NULL,
  OWNER_NAME varchar(50) NOT NULL,
  TEL varchar(16) NOT NULL,
  MASTER_GROUP_ID varchar(32) NOT NULL,
  VERSION bigint NOT NULL,
  CHECK_VIEW varchar(200),
  HOUSE_CODE varchar(32) NOT NULL,
  SOURCE_ID varchar(32) NOT NULL,
  TYPE varchar(20) NOT NULL,
  APPLY_TIME datetime NOT NULL,
  STATUS varchar(20) NOT NULL,
  SEARCH_KEY varchar(1024),
  SALE_TITLE varchar(200) NOT NULL,
  CHECK_TIME datetime NOT NULL,
  CONTRACT varchar(32),
  BUSINESS_ID varchar(32),
  MESSAGES LONGTEXT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.SELL_PROXY_PERSON
(
  CREDENTIALS_TYPE varchar(32) NOT NULL,
  CREDENTIALS_NUMBER varchar(100) NOT NULL,
  PERSON_NAME varchar(64) NOT NULL,
  TEL varchar(16) NOT NULL,
  ID varchar(32) NOT NULL,
  HOUSE_SOURCE varchar(32) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.COMPANY_SELL_INFO
(
  GROUP_ID varchar(32) NOT NULL,
  ID varchar(32) NOT NULL,
  HOUSE_SOURCE varchar(32) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


ALTER TABLE CONTRACT.HOUSE_SOURCE
  ADD FOREIGN KEY (CONTRACT)
REFERENCES CONTRACT.HOUSE_CONTRACT (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE CONTRACT.SELL_SHOW_IMG
  ADD FOREIGN KEY (HOUSE_SELL_INFO)
REFERENCES CONTRACT.HOUSE_SELL_INFO (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE CONTRACT.HOUSE_SELL_INFO
  ADD FOREIGN KEY (ID)
REFERENCES CONTRACT.HOUSE_SOURCE (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE CONTRACT.SELL_PROXY_PERSON
  ADD FOREIGN KEY (HOUSE_SOURCE)
REFERENCES CONTRACT.HOUSE_SOURCE (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

ALTER TABLE CONTRACT.COMPANY_SELL_INFO
  ADD FOREIGN KEY (HOUSE_SOURCE)
REFERENCES CONTRACT.HOUSE_SOURCE (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;


INSERT INTO CONTRACT.SYSTEM_PARAM(ID,VALUE,TYPE) VALUES('map.lat','40.12902283','STRING');
INSERT INTO CONTRACT.SYSTEM_PARAM(ID,VALUE,TYPE) VALUES('map.lng','124.33854311','STRING');
INSERT INTO CONTRACT.SYSTEM_PARAM(ID,VALUE,TYPE) VALUES('map.zoom','14','STRING');