CREATE TABLE CONTRACT.COMMIT_FILE
(
	ID varchar(32) NOT NULL,
	CONTRACT varchar(32) NOT NULL,
	UPLOAD_TIME timestamp,
	MD5 longtext,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



ALTER TABLE CONTRACT.COMMIT_FILE
	ADD FOREIGN KEY (CONTRACT)
	REFERENCES CONTRACT.HOUSE_CONTRACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


INSERT INTO SYSTEM_PARAM(ID,VALUE,DESCRIPTION,TYPE) VALUES('public_api_server','http://127.0.0.1:8090','public nginx address','STRING');

INSERT INTO CONTRACT.SYSTEM_PARAM(ID,VALUE,TYPE) VALUES('contract_address','http://192.168.248.248:9080/','STRING');
